### ISSUE TITLE
An idea.

### ISSUE THREAD

**Issue by lilfuchs** [Horizahn/hrp_pd_impound#1]
I made a much crappier system that does exactly what this does but instead of allowing anyone to get out their vehicles it required a  police officer or ideally a mechanic/impound owner to pull the vehicle out for them instead of people being able to just come take the car out especially if say the police want to put a hold on the car.

So basically what you could do is make a config system. make it so it takes say >enter a certain time period here< before the player can take it out of impound without the need of a police or mecano. 

and then make it so only police and mecano can unimpound the vehicle unless that time limit has passed. this would make much more realistic and interactive role play.

Im going to personally fork this and work on this idea slowly. but since i have irl stuff and other large development things going on it will be slow.

**Comment by Horizahn** [comment]
I've thought about giving officers and mechanics their own menu where they could configure this. Sounds pretty good to me. Feel free to give it a shot since i'm also going to be quite busy over the next couple of weeks.

**Comment by shyricaus** [comment]
I would like to add a delete in the owned_vehicles vehicle, because every time the server reboots, the guy can pick up the vehicle in the garage and he gets bugged in the h_impounded_vehicles

**Comment by shyricaus** [comment]
like that    
-- Insert vehicle into impound table
MySQL.Async.execute("INSERT INTO `impounded_vehicles` (`vehicle`, `owner`, `impounded_at`) VALUES(@vehicle, @owner, @timestamp)", {['@vehicle'] = vehicle.vehicle, ['@owner'] = vehicle.owner, ['@timestamp'] = current_time})
 
 -- Delete vehicle from garage
MySQL.Async.execute("DELETE FROM owned_vehicles WHERE plate=@plate LIMIT 1", {['@plate'] = vehicle.plate})

**Comment by Horizahn** [comment]
Dont have time atm, feel free to implement this.

Would this not delete the vehicle completely?

**Comment by shyricaus** [comment]
Yes

**Comment by shyricaus** [comment]
and place inside the impound table

**Comment by shyricaus** [comment]
because for those who use eden_garage, it has a command that every time the server restarts, the vehicles stop being false and become true in the garage

**Comment by shyricaus** [comment]
Horizahn could tell me how to add the delete in the sever.lua, since the inda is new to the program. but only if it is clear.

**Comment by shyricaus** [comment]
would not have put to the vehicle when it is imprisoned in the impound, be deleted from the garage ...

type this example I saw in another script.

      -- Insert vehicle into impound table
      MySQL.Async.execute("INSERT INTO `impounded_vehicles` (`vehicle`, `owner`, `impounded_at`) VALUES(@vehicle, @owner, @timestamp)", {['@vehicle'] = vehicle.vehicle, ['@owner'] = vehicle.owner, ['@timestamp'] = current_time})

      -- Delete vehicle from garage
      MySQL.Async.execute("DELETE FROM owned_vehicles WHERE plate=@plate LIMIT 1", {['@plate'] = vehicle.plate})

---------------------------------------------------------------------------------------------------------------------------------------------------------------

      -- Insert vehicle into owned_vehicles table
      MySQL.Async.execute("INSERT INTO `owned_vehicles` (`vehicle`, `state`, `owner`) VALUES(@vehicle, '0', @owner)", {['@vehicle'] = vehicle.vehicle, ['@owner'] = vehicle.owner})

      -- Delete vehicle from Impound Lot
      MySQL.Async.execute("DELETE FROM impounded_vehicles WHERE id=@id LIMIT 1", {['@id'] = vehicle.id})

**Comment by Horizahn** [comment]
@shyricaus https://forum.fivem.net/t/release-pd-impound-esx/152845/63?u=horizonpls

Im not going to delete the vehicle from the owned vehicles table, since I dont trust this process to go without faults at all times. If you want tho, you could do this for your own server.
