### ISSUE TITLE
Impound : bad argument #1 to 'gsub'

### ISSUE THREAD

**Issue by HalCroves** [Horizahn/hrp_pd_impound#7]
Hi o7,
To start, thank you for your great script !

I allow myself to post directly on the github, rather than on the discussion board.
Since the last version of es_extended, it is no longer possible for me to impound vehicles.

Let me explain.

- I arrive in the area, I leave the vehicle,
- I press E to access the form. 
- I fill the form and there, when I press the button "Impoud", I have error 

`...math.lua 15: bad argument #1 to 'gsub' string expected, got nill`
https://github.com/ESX-Org/es_extended/blob/faedf98f523f1efcab27dd6af6d78b82ba7b51ea/shared/modules/math.lua#L15

I tried to understand where the error came from, but I absolutely do not understand :(
I will check in the lua site, and for me the files math.lua is correct (https://www.lua.org/pil/20.3.html)

Do you have any idea where this problem comes from?

Cordially, Hal !

**Comment by YahTheDev** [comment]
Need the whole exception log, i dont know where my script calls this
function.

**Comment by HalCroves** [comment]
Thanks for you reply.

First, this a console log :
**When i impud the vehicle :** 
![image](https://user-images.githubusercontent.com/16627463/49965953-f471ca80-ff1e-11e8-81f1-332ac090b230.png)
**When i restart the script :** 
![image](https://user-images.githubusercontent.com/16627463/49966107-69dd9b00-ff1f-11e8-9b6c-69b095259cf1.png)
(for the line 108 it's another script)
Of course, i use your last release.

I slightly modified your script graphically (if you want look => https://github.com/HalCroves/hrp_pd_impound)
- Add blips
- Add Marker
- Traduction FR
Your script was working fine before the new version of es_extended


I don't know what else to give you :(

**Comment by YahTheDev** [comment]
I'd suppose it would have something to do with the following lines:

263+

```
	if (veh.plate:gsub("%s+", "") ~= data.plate:gsub("%s+", "")) then
		_ESX.ShowNotification("The processed vehicle, and nearest vehicle do not match");
		return
	end
```

If this is the case, either the local vehicle you're standing next to seems to have a nil value for plate, or the form you just filled in has a nil plate value.

If you open up the form, does it give you a plate value top right.

**Comment by HalCroves** [comment]
Yes. I have a plate value top right.

In your json.lua, there are also some gsub. I have remove the gsub value from client and server files, and i have still the same mistake.

Maybe this : 
```
local function encode_string(val)
	return '"' .. val:gsub('[%z\1-\31\\"]', escape_char) .. '"'
end
```

![image](https://user-images.githubusercontent.com/16627463/49968616-9cd75d00-ff26-11e8-8894-920c7fd34c1c.png)

**Comment by YahTheDev** [comment]
If it was an exception on the server side of the script, the exception should be logged to the server console instead of in-game I reckon.

For some reason there seem to be missing bytes when executing the NUI callback. I'm not sure why, any idea what has changed recently within FiveM or ESX? I haven't been following along.

**Comment by YahTheDev** [comment]
There's a couple of open threads on the forum about the missing bytes issue. No solutions that I can find atm and I have no idea what the issue could be. If other players start reporting this I might take a deep dive into this.

**Comment by HalCroves** [comment]
There are a lot of artifacts between your latest version and today.

Es_extended has been updated several times, and it seems to me that there was a problem with NUI not long ago.

After I do not know more. It annoys me, your script is just perfect. I will try to find a solution.

No worries, thanks for the time spent on this anomaly. I would come back if I found something.
o/


Last note for me.
The problem would come from here "**Error during NUI callback impound**"
```
RegisterNUICallback('impound', function(data, cb)
	local v = ESX.Game.GetClosestVehicle()
	local veh = ESX.Game.GetVehicleProperties(v)
	
	veh.engineHealth = GetVehicleEngineHealth(v)
	veh.bodyHealth = GetVehicleBodyHealth(v)
	veh.fuelLevel = GetVehicleFuelLevel(v)
	veh.oilLevel = GetVehicleOilLevel(v)
	veh.petrolTankHealth = GetVehiclePetrolTankHealth(v)
	veh.tyresburst = {}
	for i = 1, 7 do
		res = IsVehicleTyreBurst(v, i, false)
		if res ~= nil then
			veh.tyresburst[#veh.tyresburst+1] = res
			if res == false then
				res = IsVehicleTyreBurst(v, i, true)
				veh.tyresburst[#veh.tyresburst] = res
			end
		else
			veh.tyresburst[#veh.tyresburst+1] = false
		end
	end
	
	veh.windows = {}
	for i = 1, 13 do
		res = IsVehicleWindowIntact(v, i)
		if res ~= nil then
			veh.windows[#veh.windows+1] = res
		else
			veh.windows[#veh.windows+1] = true
		end
	end
	
	if (veh.plate:gsub("%s+", "") ~= data.plate:gsub("%s+", "")) then
		ESX.ShowNotification("The processed vehicle, and nearest vehicle do not match");
		return
	end

	
	data.vehicle = json.encode(veh)
	data.identifier = VehicleAndOwner.identifier
	
	TriggerServerEvent('HRP:Impound:ImpoundVehicle', data)
	
	ESX.Game.DeleteVehicle(ESX.Game.GetClosestVehicle())
	
	DisableImpoundMenu()
	-- cb('ok')
end)
```

**Comment by HalCroves** [comment]
I may have a stronger track. By removing a good part of the function, I manage to execute the script!

Without the characteristics of the vehicle, it is well impound and save in data base.

```
RegisterNUICallback('impound', function(data, cb)
	-- local v = ESX.Game.GetClosestVehicle()
	-- local veh = ESX.Game.GetVehicleProperties(v)

	data.vehicle = json.encode(veh);
	data.identifier = VehicleAndOwner.identifier;
	
	TriggerServerEvent('HRP:Impound:ImpoundVehicle', data)
	
	-- ESX.Game.DeleteVehicle(ESX.Game.GetClosestVehicle())
	
	DisableImpoundMenu()
	-- cb('ok')
end)
```
HRP: Impounding vehicle: 89YEM666
![image](https://user-images.githubusercontent.com/16627463/49971365-8208e680-ff2e-11e8-8b1e-b0b2ce172687.png)

And i think the value of **local v = ESX.Game.GetClosestVehicle()** is nil because is missing the coordinates of the vehicle?

**Comment by HalCroves** [comment]
And finally (for tonight)

```lua
RegisterNUICallback('impound', function(data, cb)

	local playerPed = PlayerPedId()
	local coords    = GetEntityCoords(playerPed)

	local v = GetClosestVehicle(coords.x, coords.y, coords.z, 5.0, 0, 71)
	-- print(v)

	local veh = ESX.Game.GetVehicleProperties(v)
	-- print(veh)

	
	veh.engineHealth = GetVehicleEngineHealth(v)
	veh.bodyHealth = GetVehicleBodyHealth(v)
	veh.fuelLevel = GetVehicleFuelLevel(v)
	veh.oilLevel = GetVehicleOilLevel(v)
	veh.petrolTankHealth = GetVehiclePetrolTankHealth(v)
	veh.tyresburst = {}
	for i = 1, 7 do
		res = IsVehicleTyreBurst(v, i, false)
		if res ~= nil then
			veh.tyresburst[#veh.tyresburst+1] = res
			if res == false then
				res = IsVehicleTyreBurst(v, i, true)
				veh.tyresburst[#veh.tyresburst] = res
			end
		else
			veh.tyresburst[#veh.tyresburst+1] = false
		end
	end
	
	veh.windows = {}
	for i = 1, 13 do
		res = IsVehicleWindowIntact(v, i)
		if res ~= nil then
			veh.windows[#veh.windows+1] = res
		else
			veh.windows[#veh.windows+1] = true
		end
	end
	
	if (veh.plate:gsub("%s+", "") ~= data.plate:gsub("%s+", "")) then
		ESX.ShowNotification(_U('vehicle_plate_error'))
		return
	end
	
	data.vehicle = veh;
	data.identifier = VehicleAndOwner.identifier;
	
	TriggerServerEvent('HRP:Impound:ImpoundVehicle', data)
	
	ESX.Game.DeleteVehicle(ESX.Game.GetClosestVehicle())
	
	DisableImpoundMenu()
	-- cb('ok')
end)
```

And in server.lua, replace : 
```sql
['@vehicle']		= form.vehicle,
```
By : 
```sql
['@vehicle']		= json.encode(form.vehicle),
```
